namespace WallstopStudios.DxCommandTerminal.SourceGenerators
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;

    internal static class CatalogEmitter
    {
        internal static SymbolDisplayFormat FullyQualified =>
            SymbolDisplayFormat.FullyQualifiedFormat;

        private const string BinderFieldNameFormat = "_boundHandler{0}";
        private const string BinderMethodNameFormat = "BindHandler{0}";

        internal static string Emit(List<CommandModel> commands)
        {
            StringBuilder builder = new StringBuilder(4096);
            bool needsReflection = false;

            foreach (CommandModel command in commands)
            {
                if (!command.HasValidSignature || !command.DirectlyBindable)
                {
                    needsReflection = true;
                    break;
                }
            }

            builder.Append("// <auto-generated>\n");
            builder.Append(
                "//     Generated by WallstopStudios.DxCommandTerminal.SourceGenerators.\n"
            );
            builder.Append("//     Do not edit; changes are overwritten on every compilation.\n");
            builder.Append("// </auto-generated>\n");
            builder.Append("#pragma warning disable 612 // Obsolete member\n");
            builder.Append("#pragma warning disable 618 // Obsolete member\n");
            builder.Append("#pragma warning disable 1591 // Missing XML comment\n");
            builder.Append("\n");
            builder.Append("namespace WallstopStudios.DxCommandTerminal.Generated\n");
            builder.Append("{\n");
            builder.Append("    using System;\n");
            builder.Append("    using System.Collections.Generic;\n");
            if (needsReflection)
            {
                builder.Append("    using System.Reflection;\n");
            }
            builder.Append("    using global::WallstopStudios.DxCommandTerminal.Backend;\n");
            builder.Append("\n");
            builder.Append("    internal static class CommandCatalog\n");
            builder.Append("    {\n");
            builder.Append(
                "        private static readonly List<CommandCatalogEntry> Entries = Build();\n"
            );
            builder.Append("\n");
            builder.Append(
                "        public static void Collect(List<CommandCatalogEntry> entries)\n"
            );
            builder.Append("        {\n");
            builder.Append("            if (entries == null)\n");
            builder.Append("            {\n");
            builder.Append("                throw new ArgumentNullException(\"entries\");\n");
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            entries.AddRange(Entries);\n");
            builder.Append("        }\n");
            builder.Append("\n");
            builder.Append("        private static List<CommandCatalogEntry> Build()\n");
            builder.Append("        {\n");
            builder.Append(
                "            List<CommandCatalogEntry> entries = new List<CommandCatalogEntry>();\n"
            );

            int commandIndex = 0;
            bool needsUnboundFinder = false;
            for (int i = 0; i < commands.Count; i++)
            {
                CommandModel command = commands[i];
                if (EmitCommand(builder, commandIndex, command, ref needsUnboundFinder))
                {
                    commandIndex++;
                }
            }

            builder.Append("            return entries;\n");
            builder.Append("        }\n");

            if (needsUnboundFinder)
            {
                EmitUnboundMethodFinder(builder);
            }

            for (int i = 0; i < commands.Count; i++)
            {
                CommandModel command = commands[i];
                if (command.HasValidSignature && !command.DirectlyBindable)
                {
                    EmitCachedBinder(builder, i, command);
                }
            }

            builder.Append("    }\n");
            builder.Append("}\n");
            return builder.ToString();
        }

        private static bool EmitCommand(
            StringBuilder builder,
            int commandIndex,
            CommandModel command,
            ref bool needsUnboundFinder
        )
        {
            builder.Append("\n");
            builder
                .Append("            // ")
                .Append(commandIndex)
                .Append(": command '")
                .Append(command.CommandName.Replace("\r", string.Empty).Replace("\n", string.Empty))
                .Append("' from method ")
                .Append(command.MethodName)
                .Append('\n');
            builder.Append("            entries.Add(new CommandCatalogEntry(\n");
            AppendLiteral(builder, command.CommandName, depth: 4);
            builder.Append(",\n");
            AppendLiteral(builder, command.MethodName, depth: 4);
            builder.Append(",\n");
            builder
                .Append("                ")
                .Append(
                    command.MinArgCount.ToString(System.Globalization.CultureInfo.InvariantCulture)
                )
                .Append(", ")
                .Append(
                    command.MaxArgCount.ToString(System.Globalization.CultureInfo.InvariantCulture)
                )
                .Append(",\n");
            AppendLiteral(builder, command.Help, depth: 4);
            builder.Append(",\n");
            AppendLiteral(builder, command.Hint, depth: 4);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.AddToHistory);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.EditorOnly);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.DevelopmentOnly);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.IsDefault);
            builder.Append(",\n");

            if (command.HasValidSignature)
            {
                if (command.DirectlyBindable)
                {
                    builder.Append("                new Func<Action<CommandArg[]>>(delegate\n");
                    builder.Append("                {\n");
                    builder
                        .Append("                    return new Action<CommandArg[]>(")
                        .Append(command.ContainingTypeDisplay)
                        .Append('.')
                        .Append(command.MethodName)
                        .Append(");\n");
                    builder.Append("                }),\n");
                    builder.Append("                null\n");
                }
                else
                {
                    builder
                        .Append("                new Func<Action<CommandArg[]>>(")
                        .Append(Format(BinderMethodNameFormat, commandIndex))
                        .Append("),\n");
                    builder.Append("                null\n");
                }
            }
            else
            {
                builder.Append("                null,\n");
                builder.Append("                new Func<MethodInfo>(delegate\n");
                builder.Append("                {\n");
                if (command.ExactSignatureAddressable)
                {
                    builder.Append("                    return typeof(");
                    builder.Append(command.ContainingTypeDisplay);
                    builder.Append(").GetMethod(\n");
                    AppendLiteral(builder, command.MethodName, depth: 6);
                    builder.Append(",\n");
                    builder.Append(
                        "                        BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic,\n"
                    );
                    builder.Append("                        null,\n");
                    builder.Append("                        new Type[]\n");
                    builder.Append("                        {\n");
                    for (int i = 0; i < command.ParameterTypeExpressions.Length; i++)
                    {
                        builder.Append("                            ");
                        builder.Append(command.ParameterTypeExpressions[i]);
                        builder.Append(
                            i == command.ParameterTypeExpressions.Length - 1 ? "\n" : ",\n"
                        );
                    }
                    builder.Append("                        },\n");
                    builder.Append("                        null\n");
                    builder.Append("                    );\n");
                }
                else
                {
                    needsUnboundFinder = true;
                    builder.Append("                    return FindMethodByName(\n");
                    builder.Append("                        typeof(");
                    builder.Append(command.ContainingTypeDisplay);
                    builder.Append("),\n");
                    AppendLiteral(builder, command.MethodName, depth: 6);
                    builder.Append(",\n");
                    builder
                        .Append("                        ")
                        .Append(
                            command.ParameterTypeExpressions.Length.ToString(
                                System.Globalization.CultureInfo.InvariantCulture
                            )
                        )
                        .Append("\n");
                    builder.Append("                    );\n");
                }
                builder.Append("                })\n");
            }

            builder.Append("            ));\n");
            return true;
        }

        private static void EmitUnboundMethodFinder(StringBuilder builder)
        {
            builder.Append("\n");
            builder.Append("        private static MethodInfo FindMethodByName(\n");
            builder.Append("            Type type,\n");
            builder.Append("            string name,\n");
            builder.Append("            int parameterCount\n");
            builder.Append("        )\n");
            builder.Append("        {\n");
            builder.Append("            MethodInfo[] methods = type.GetMethods(\n");
            builder.Append(
                "                BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic\n"
            );
            builder.Append("            );\n");
            builder.Append("            for (int i = 0; i < methods.Length; i++)\n");
            builder.Append("            {\n");
            builder.Append("                MethodInfo method = methods[i];\n");
            builder.Append("                if (\n");
            builder.Append("                    method.Name == name\n");
            builder.Append(
                "                    && method.GetParameters().Length == parameterCount\n"
            );
            builder.Append("                )\n");
            builder.Append("                {\n");
            builder.Append("                    return method;\n");
            builder.Append("                }\n");
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            return null;\n");
            builder.Append("        }\n");
        }

        private static void EmitCachedBinder(
            StringBuilder builder,
            int binderIndex,
            CommandModel command
        )
        {
            string fieldName = Format(BinderFieldNameFormat, binderIndex);
            string methodName = Format(BinderMethodNameFormat, binderIndex);

            builder.Append("\n");
            builder
                .Append("        private static Action<CommandArg[]> ")
                .Append(fieldName)
                .Append(";\n");
            builder.Append("\n");
            builder
                .Append("        private static Action<CommandArg[]> ")
                .Append(methodName)
                .Append("()\n");
            builder.Append("        {\n");
            builder.Append("            if (").Append(fieldName).Append(" == null)\n");
            builder.Append("            {\n");
            builder
                .Append("                ")
                .Append(fieldName)
                .Append(" = (Action<CommandArg[]>)\n");
            builder.Append("                    Delegate.CreateDelegate(\n");
            builder.Append("                        typeof(Action<CommandArg[]>),\n");
            builder.Append("                        typeof(");
            builder.Append(command.ContainingTypeDisplay);
            builder.Append(").GetMethod(\n");
            AppendLiteral(builder, command.MethodName, depth: 6);
            builder.Append(",\n");
            builder.Append(
                "                            BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic,\n"
            );
            builder.Append("                            null,\n");
            builder.Append("                            new Type[]\n");
            builder.Append("                            {\n");
            for (int i = 0; i < command.ParameterTypeExpressions.Length; i++)
            {
                builder.Append("                                ");
                builder.Append(command.ParameterTypeExpressions[i]);
                builder.Append(i == command.ParameterTypeExpressions.Length - 1 ? "\n" : ",\n");
            }
            builder.Append("                            },\n");
            builder.Append("                            null\n");
            builder.Append("                        )\n");
            builder.Append("                    );\n");
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            return ");
            builder.Append(fieldName);
            builder.Append(";\n");
            builder.Append("        }\n");
        }

        private static void AppendLiteral(StringBuilder builder, string value, int depth)
        {
            string indentation = new string(' ', depth * 4);
            builder.Append(indentation);
            builder.Append(
                value == null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true)
            );
        }

        private static void AppendBoolLiteral(StringBuilder builder, bool value)
        {
            builder.Append("                ").Append(value ? "true" : "false");
        }

        private static string Format(string format, int index)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, format, index);
        }
    }
}
