namespace WallstopStudios.DxCommandTerminal.SourceGenerators
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;

    internal static class CatalogEmitter
    {
        internal static SymbolDisplayFormat FullyQualified =>
            SymbolDisplayFormat.FullyQualifiedFormat;

        /*
            Generated code references every type through fully qualified
            global:: names so a consumer type declared in an enclosing
            namespace (for example `WallstopStudios.DxCommandTerminal.Func`)
            cannot hijack resolution; no using directives are emitted.
         */
        private const string ArgumentType =
            "global::WallstopStudios.DxCommandTerminal.Backend.CommandArg";

        private const string HandlerType = ArgumentType + "[]";

        private const string BinderType = "global::System.Action<" + HandlerType + ">";

        private const string BinderFactoryType = "global::System.Func<" + BinderType + ">";

        private const string EntryType =
            "global::WallstopStudios.DxCommandTerminal.Backend.CommandCatalogEntry";

        private const string EntryListType =
            "global::System.Collections.Generic.List<" + EntryType + ">";

        private const string BindingFlagsType = "global::System.Reflection.BindingFlags";

        private const string BindingFlagsExpression =
            BindingFlagsType
            + ".Static | "
            + BindingFlagsType
            + ".Public | "
            + BindingFlagsType
            + ".NonPublic";

        private const string BinderFieldNameFormat = "_boundHandler{0}";
        private const string BinderMethodNameFormat = "BindHandler{0}";

        internal static string Emit(List<CommandModel> commands)
        {
            StringBuilder builder = new StringBuilder(4096);
            bool needsUnboundFinder = false;

            foreach (CommandModel command in commands)
            {
                if (!command.HasValidSignature && !command.ExactSignatureAddressable)
                {
                    needsUnboundFinder = true;
                    break;
                }
            }

            builder.Append("// <auto-generated>\n");
            builder.Append(
                "//     Generated by WallstopStudios.DxCommandTerminal.SourceGenerators.\n"
            );
            builder.Append("//     Do not edit; changes are overwritten on every compilation.\n");
            builder.Append("// </auto-generated>\n");
            builder.Append("#pragma warning disable 612 // Obsolete member\n");
            builder.Append("#pragma warning disable 618 // Obsolete member\n");
            builder.Append("#pragma warning disable 1591 // Missing XML comment\n");
            builder.Append("\n");
            builder.Append("namespace WallstopStudios.DxCommandTerminal.Generated\n");
            builder.Append("{\n");
            builder.Append("    internal static class CommandCatalog\n");
            builder.Append("    {\n");
            builder.Append(
                "        private static readonly " + EntryListType + " Entries = Build();\n"
            );
            builder.Append("\n");
            builder.Append("        public static void Collect(");
            builder.Append(EntryListType);
            builder.Append(" entries)\n");
            builder.Append("        {\n");
            builder.Append("            if (entries == null)\n");
            builder.Append("            {\n");
            builder.Append(
                "                throw new global::System.ArgumentNullException(\"entries\");\n"
            );
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            entries.AddRange(Entries);\n");
            builder.Append("        }\n");
            builder.Append("\n");
            builder.Append("        private static " + EntryListType + " Build()\n");
            builder.Append("        {\n");
            builder.Append("            " + EntryListType + " entries = new ");
            builder.Append(EntryListType);
            builder.Append("();\n");

            for (int i = 0; i < commands.Count; i++)
            {
                EmitCommand(builder, i, commands[i]);
            }

            builder.Append("            return entries;\n");
            builder.Append("        }\n");

            if (needsUnboundFinder)
            {
                EmitUnboundMethodFinder(builder);
            }

            for (int i = 0; i < commands.Count; i++)
            {
                CommandModel command = commands[i];
                if (command.HasValidSignature && !command.DirectlyBindable)
                {
                    EmitCachedBinder(builder, i, command);
                }
            }

            builder.Append("    }\n");
            builder.Append("}\n");
            return builder.ToString();
        }

        private static void EmitCommand(
            StringBuilder builder,
            int commandIndex,
            CommandModel command
        )
        {
            builder.Append("\n");
            builder
                .Append("            // ")
                .Append(commandIndex)
                .Append(": command '")
                .Append(command.CommandName.Replace("\r", string.Empty).Replace("\n", string.Empty))
                .Append("' from method ")
                .Append(command.MethodName)
                .Append('\n');
            builder.Append("            entries.Add(new ");
            builder.Append(EntryType);
            builder.Append("(\n");
            AppendLiteral(builder, command.CommandName, depth: 4);
            builder.Append(",\n");
            AppendLiteral(builder, command.MethodName, depth: 4);
            builder.Append(",\n");
            builder
                .Append("                ")
                .Append(
                    command.MinArgCount.ToString(System.Globalization.CultureInfo.InvariantCulture)
                )
                .Append(", ")
                .Append(
                    command.MaxArgCount.ToString(System.Globalization.CultureInfo.InvariantCulture)
                )
                .Append(",\n");
            AppendLiteral(builder, command.Help, depth: 4);
            builder.Append(",\n");
            AppendLiteral(builder, command.Hint, depth: 4);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.AddToHistory);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.EditorOnly);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.DevelopmentOnly);
            builder.Append(",\n");
            AppendBoolLiteral(builder, command.IsDefault);
            builder.Append(",\n");

            if (command.HasValidSignature)
            {
                if (command.DirectlyBindable)
                {
                    builder.Append("                new ");
                    builder.Append(BinderFactoryType);
                    builder.Append("(delegate\n");
                    builder.Append("                {\n");
                    builder.Append("                    return new ");
                    builder.Append(BinderType);
                    builder.Append("(");
                    builder.Append(command.ContainingTypeDisplay);
                    builder.Append('.');
                    builder.Append(command.MethodNameIdentifierDisplay);
                    builder.Append(");\n");
                    builder.Append("                }),\n");
                    builder.Append("                null\n");
                }
                else
                {
                    builder.Append("                new ");
                    builder.Append(BinderFactoryType);
                    builder.Append("(");
                    builder.Append(Format(BinderMethodNameFormat, commandIndex));
                    builder.Append("),\n");
                    builder.Append("                null\n");
                }
            }
            else
            {
                builder.Append("                null,\n");
                builder.Append(
                    "                new global::System.Func<global::System.Reflection.MethodInfo>(delegate\n"
                );
                builder.Append("                {\n");
                if (command.ExactSignatureAddressable)
                {
                    builder.Append("                    return typeof(");
                    builder.Append(command.ContainingTypeDisplay);
                    builder.Append(").GetMethod(\n");
                    AppendLiteral(builder, command.MethodName, depth: 6);
                    builder.Append(",\n");
                    builder.Append("                        ");
                    builder.Append(BindingFlagsExpression);
                    builder.Append(",\n");
                    builder.Append("                        null,\n");
                    builder.Append("                        new global::System.Type[]\n");
                    builder.Append("                        {\n");
                    for (int i = 0; i < command.ParameterTypeExpressions.Length; i++)
                    {
                        builder.Append("                            ");
                        builder.Append(command.ParameterTypeExpressions[i]);
                        builder.Append(
                            i == command.ParameterTypeExpressions.Length - 1 ? "\n" : ",\n"
                        );
                    }
                    builder.Append("                        },\n");
                    builder.Append("                        null\n");
                    builder.Append("                    );\n");
                }
                else
                {
                    builder.Append("                    return FindMethodByName(\n");
                    builder.Append("                        typeof(");
                    builder.Append(command.ContainingTypeDisplay);
                    builder.Append("),\n");
                    AppendLiteral(builder, command.MethodName, depth: 6);
                    builder.Append(",\n");
                    builder.Append("                        ");
                    builder.Append(
                        command.ParameterTypeExpressions.Length.ToString(
                            System.Globalization.CultureInfo.InvariantCulture
                        )
                    );
                    builder.Append(",\n");
                    builder.Append("                        ");
                    builder.Append(command.IsMethodGeneric ? "true" : "false");
                    builder.Append("\n");
                    builder.Append("                    );\n");
                }
                builder.Append("                })\n");
            }

            builder.Append("            ));\n");
        }

        private static void EmitUnboundMethodFinder(StringBuilder builder)
        {
            builder.Append("\n");
            builder.Append(
                "        private static global::System.Reflection.MethodInfo FindMethodByName(\n"
            );
            builder.Append("            global::System.Type type,\n");
            builder.Append("            string name,\n");
            builder.Append("            int parameterCount,\n");
            builder.Append("            bool isGeneric\n");
            builder.Append("        )\n");
            builder.Append("        {\n");
            builder.Append(
                "            global::System.Reflection.MethodInfo[] methods = type.GetMethods(\n"
            );
            builder.Append("                ");
            builder.Append(BindingFlagsExpression);
            builder.Append("\n");
            builder.Append("            );\n");
            builder.Append("            for (int i = 0; i < methods.Length; i++)\n");
            builder.Append("            {\n");
            builder.Append(
                "                global::System.Reflection.MethodInfo method = methods[i];\n"
            );
            builder.Append("                if (\n");
            builder.Append("                    method.Name == name\n");
            builder.Append(
                "                    && method.GetParameters().Length == parameterCount\n"
            );
            builder.Append(
                "                    && method.IsGenericMethodDefinition == isGeneric\n"
            );
            builder.Append("                )\n");
            builder.Append("                {\n");
            builder.Append("                    return method;\n");
            builder.Append("                }\n");
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            return null;\n");
            builder.Append("        }\n");
        }

        private static void EmitCachedBinder(
            StringBuilder builder,
            int binderIndex,
            CommandModel command
        )
        {
            string fieldName = Format(BinderFieldNameFormat, binderIndex);
            string methodName = Format(BinderMethodNameFormat, binderIndex);

            builder.Append("\n");
            builder
                .Append("        private static ")
                .Append(BinderType)
                .Append(" ")
                .Append(fieldName)
                .Append(";\n");
            builder.Append("\n");
            builder
                .Append("        private static ")
                .Append(BinderType)
                .Append(" ")
                .Append(methodName)
                .Append("()\n");
            builder.Append("        {\n");
            builder.Append("            if (");
            builder.Append(fieldName);
            builder.Append(" == null)\n");
            builder.Append("            {\n");
            builder.Append("                ");
            builder.Append(fieldName);
            builder.Append(" = (");
            builder.Append(BinderType);
            builder.Append(")\n");
            builder.Append("                    global::System.Delegate.CreateDelegate(\n");
            builder.Append("                        typeof(");
            builder.Append(BinderType);
            builder.Append("),\n");
            builder.Append("                        typeof(");
            builder.Append(command.ContainingTypeDisplay);
            builder.Append(").GetMethod(\n");
            AppendLiteral(builder, command.MethodName, depth: 6);
            builder.Append(",\n");
            builder.Append("                            ");
            builder.Append(BindingFlagsExpression);
            builder.Append(",\n");
            builder.Append("                            null,\n");
            builder.Append("                            new global::System.Type[]\n");
            builder.Append("                            {\n");
            for (int i = 0; i < command.ParameterTypeExpressions.Length; i++)
            {
                builder.Append("                                ");
                builder.Append(command.ParameterTypeExpressions[i]);
                builder.Append(i == command.ParameterTypeExpressions.Length - 1 ? "\n" : ",\n");
            }
            builder.Append("                            },\n");
            builder.Append("                            null\n");
            builder.Append("                        )\n");
            builder.Append("                    );\n");
            builder.Append("            }\n");
            builder.Append("\n");
            builder.Append("            return ");
            builder.Append(fieldName);
            builder.Append(";\n");
            builder.Append("        }\n");
        }

        private static void AppendLiteral(StringBuilder builder, string value, int depth)
        {
            string indentation = new string(' ', depth * 4);
            builder.Append(indentation);
            builder.Append(
                value == null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true)
            );
        }

        private static void AppendBoolLiteral(StringBuilder builder, bool value)
        {
            builder.Append("                ").Append(value ? "true" : "false");
        }

        private static string Format(string format, int index)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, format, index);
        }
    }
}
